### ISSUE TITLE
TODO List for the homepage

### ISSUE THREAD

**Issue by StefanGreve** [StefanGreve/htw-ag#1]
Things that need to be work on in the future: This list targets the homepage only for the time being.

- [ ] `MISSING` - introductory text for Smart Home project on `home.html`
- [ ] `MISSING` - introductory text for Artificial Intelligence project on `home.html`
- [ ] `MISSING` - validate email input on client side
- [ ] `ENHANCEMENT` - fix mail form styling for bad input cases
- [ ] `MISSING` - implement send function
- [ ] `MISSING` - add most recent news article in-between `introduction` and `about-us` sections

**Comment by StefanGreve** [comment]
(Last commit also added a google recaptcha field.)
