### ISSUE TITLE
TODO List for Admin Dashboard

### ISSUE THREAD

**Issue by StefanGreve** [StefanGreve/htw-ag#4]
- [ ] Add Login styles to `login.html` (move styles from `_home.scss` to `main.scss` and derive rules from there)
- [ ] Add Registration Page (including `RegisterForm()` form class)
- [ ] Add DB scheme for users
- [ ] Implement `register()` method as new view
- [ ] Implement `login()` method as new view
- [ ] Update Wiki page (Google Recaptcha)
- [ ] Add barebones admin dashboard that is hidden from the public
